### PR TITLE
Package updates to fix security issues

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/brave-browser/issues/1846
fix https://github.com/brave/brave-browser/issues/1845

### CODE REVIEW

**Comment by diracdeltas** [comment]
one sec, travis is failing because the npm version on it is too old to support audit https://travis-ci.org/brave/brave-extension/jobs/446351002

**Comment by diracdeltas** [comment]
travis fixed

**Comment by diracdeltas** [comment]
related: https://github.com/brave/brave-browser/issues/1853

**Comment by bbondy** [comment]
I did for this one, but pls make sure issues that are closed are in a milestone and PRs have a label which indicates where they were merged to. Thanks!

**Pull request merged**
