### PR TITLE
Shields v2 GA version

### PR DESCRIPTION
**Pull request by cezaraugusto**
`npm run test-unit`

closes https://github.com/brave/brave-browser/issues/1339
closes https://github.com/brave/brave-browser/issues/771
closes https://github.com/brave/brave-browser/issues/507
closes https://github.com/brave/brave-browser/issues/471

### CODE REVIEW

**Comment by srirambv** [comment]
> chrome://settings/shields doesn't seem routable; 

This is mentioned in the spec that it should be open that. Currently direct link to open Global shields settings isn't implemented so this should be changed after thats done.

**Comment by srirambv** [comment]
Also noticed there is not details shown of items that are blocked. Is this being worked on a different issue?

**Comment by bsclifton** [comment]
@srirambv I believe that will be covered in https://github.com/brave/brave-browser/issues/1196 (and it may show under advanced). Maybe @rebron or @karenkliu can confirm?

**Comment by rebron** [comment]
per @srirambv and @bsclifton notes @cezaraugusto 

- Let's fix the drop down text to make visible.
Site icon size can be fixed later.
Let's get the cookie block count fixed.
Link to main settings page is fine for now.

- Let's go with sri's text changes
All device recognition blocked to 'Block all device recognition'
All device recognition allowed to 'Allow all device recognition'
All script blocked to 'Block all script'
All cookies allowed to 'Allow all cookies'
All cookies blocked to 'Block all cookies'

The https toggle is out by design and cleared by security team. We're showing connections encrypted and have it as global setting instead.

**Comment by rebron** [comment]
per discussion with @cezaraugusto and @bsclifton we'll also display ads and trackers blocked when a user selects Ad and Trackers row. Content should be the same as in current shields.

**Comment by karenkliu** [comment]
Just catching up here; I agree with most of the comments above except:

- The dropdown menu isn't matching spec; It should look like this:
group 4
The text should be visible even without hover, also it needs more padding on all sides. 

- Regarding the naming: 
The design rationale behind why the grammatically inconsistent labels is because _____ blocked, is easier for the user to recognize rather than scanning a long list of Blocked ____, Blocked ____, etc. 
However I don't want to hold this up anymore than it is so just leave it for now and we can review the labels at a later point. 

- "Down" being this color is correct:
screen shot 2018-10-12 at 11 05 52 am 
It is grey instead of red to reinforce the association that Shields is in a disabled state. Do not change this to red.

Lastly, I feel that for next round (1.0) when we're shipping shields again, it would be helpful for everyone including QA to be aware of what's in the design, influence it, and voice concerns/feedback, before it gets to dev-QA and causes a time-crunch at last minute. My apologies for not being aware that more people needed to have eyes on the design before @rebron and I put the Shields design into Github. I wasn't aware of all the stakeholders who should have been part of the design process. We'll do better next time! A retro might be a good thing to schedule after all this craziness is over so we can figure out how to make this process smoother for everyone.

**Comment by cezaraugusto** [comment]
closing in favor of https://github.com/brave/brave-extension/pull/78

**Pull request closed without merging**
