### PR TITLE
new Shields 

### PR DESCRIPTION
**Pull request by cezaraugusto**
```npm run test-unit```

closes brave/brave-browser#1339
closes brave/brave-browser#771
closes brave/brave-browser#507
closes brave/brave-browser#471

### CODE REVIEW

**Comment by bsclifton** [comment]
Some notes for reviewers after @cezaraugusto, @tomlowenthal, and myself met 😄 
- This PR should functionally match what is in place today
- brave-core has been missing the `Allow until restart` option, which is captured in https://github.com/brave/brave-browser/issues/188
- both Muon and brave-core are missing the "Allow forever" option, which is captured in https://github.com/brave/brave-browser/issues/1889

**Comment by bsclifton** [comment]
We should probably hide the `Allow all` and/or `Block all` if there are 0 items blocked
screen shot 2018-10-29 at 3 43 37 pm

**Comment by bsclifton** [comment]
Even when I hover over these entries (blocked resources), there doesn’t appear to be a way to either see the full resource or (when selecting manually and copy/pasting) copying the full resource to the clipboard

screen shot 2018-10-29 at 3 46 34 pm

**Comment by bsclifton** [comment]
Kind of a weird white box shown after the origin when you inspect scripts blocked:
screen shot 2018-10-29 at 4 00 21 pm

**Comment by bsclifton** [comment]
Nitpick: kind of a weird looking focus ring? Important to show I believe, for keyboard users. But the ring extends itself into the counter
omg-focus-ring

**Comment by bsclifton** [comment]
Here’s one that seems to be Windows specific; and since this is supposed to be a native drop-down, I’m not sure what is happening?
(text is a little hard to read) 
screen shot 2018-10-29 at 4 16 44 pm

Existing one (in our live release) doesn't seem to have any color issues:
screen shot 2018-10-29 at 4 21 01 pm

**Comment by yrliou** [comment]
reproduced https://github.com/brave/brave-extension/pull/78#issuecomment-434158345 in current brave-core and browser-laptop, so I think we should open a separate issue to track this one.

**Comment by bsclifton** [comment]
@diracdeltas since that behavior was present before, I created https://github.com/brave/brave-browser/issues/1901 to track it

While this new approach might make that more visible, the bug was present before. I'd like to propose approving and then fixing in 0.57.x. We could then ask folks if uplifting the fix to 0.56.x would be appropriate

**Pull request merged**
