### PR TITLE
Travis optimizations; Switched from yarn to npm

### PR DESCRIPTION
**Pull request by NejcZdovc**
- removed unnecessary test-suite
- removed yarn and replace it with npm, so that we can run npm audit
- added mode to webpack config files

### CODE REVIEW

**Comment by NejcZdovc** [comment]
currently failing because audit is failing https://travis-ci.org/brave/brave-extension/jobs/388211057#L661. Will try to fix it

**Comment by bbondy** [comment]
Sorry @NejcZdovc this is bitrot due to something I merged from Cezar, could you rebase?

**Comment by bsclifton** [comment]
Closing since this has been sitting for a while. @NejcZdovc please re-open if you're able to rebase 😄

**Comment by NejcZdovc** [comment]
@bsclifton @bbondy now sure what is the latest on this topic. If npm, then I can easily update this PR

**Comment by bsclifton** [comment]
I only use `npm`; not sure what others use

**Comment by NejcZdovc** [comment]
me too

**Pull request closed without merging**
